### PR TITLE
Cleanup build

### PR DESCRIPTION
**Pull request by noirbizarre**
This pull request intend to cleanup the build.
- Drop bower and only use NPM modules
- Upgrade some webpack dependencies
- Make tests runs.

### CODE REVIEW

**Comment by davidbgk** [comment]
Looks good to me except maybe removing commented lines?

**Comment by noirbizarre** [comment]
Yes I know, the last commit is a work in progress.
Test are not passing yet (not even launching :/)

**Comment by noirbizarre** [comment]
Good to review: tests are running and passing ! :)

**Comment by davidbgk** [comment]
Not sure to understand all ins and outs but it looks good to me. Should we run tests for/via Github too to check before merging?

**Comment by noirbizarre** [comment]
I think we should.
I will setup Travis after the merge

**Pull request merged**
